apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
  namespace: music-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: moonlight
      containers:
      - name: music-service
        image: music-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: music-service
  namespace: music-app
spec:
  type: NodePort
  selector:
    app: music-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081